### ISSUE TITLE
Background Position and Border Color Missing

### ISSUE THREAD

**Issue by wongbsn** [Jam3/f1-dom#3]

**Comment by mikkoh** [comment]
@wongbsn the purpose of `f1-dom` is not to cover every css property.

The idea is that it would use a limited set of properties that you can change in order to be able to make your ui reusable from platform to platform. Granted it does handle things like `background` which I think is a bit of a misstep on my part.

Also if we do add in background position you should be able to set a background image also through `f1-dom`.

One of our major issues has been creative X has said "hey could you bring this button from Y project to this project" and we'll have to say "no sorry that project was built in PIXI and this one is built in HTML/DOM".

I'm still trying to figure out whats the plan of attack in the case where you need something like background position. Maybe we can talk about what you're trying to implement and see if there are other solutions that would be able to create more reusable ui.

It should also be noted that `f1-dom` is simply an array of functions that you can add a custom parser function to but again this will make the ui less transportable from project to project.
